server:
  port: 8080

spring:
  application:
    name: gateway-server

  main:
    web-application-type: reactive

  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/company/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/deliveries/**

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/hub/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**

        - id: prediction-service
          uri: lb://prediction-service
          predicates:
            - Path=/api/predictions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


jwt:
  secret: my-secret-key-my-secret-key-my-secret-key
  issuer: sixpang-auth