spring:
  application:
    name: company-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: company_service
        show_sql: true
        format_sql: true

springdoc:
  packages-to-scan: org.sixpang.companyservice.presentation
  swagger-ui:
    disable-swagger-default-url: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}