@host = http://localhost:51261
@contentType = application/json
@companyId = 3bfc578e-51bd-4a22-8926-7c368d23498a

### 회원 생성 - HUB_MANAGER
POST http://localhost:51261/api/users
Content-Type: application/json

{
  "email": "company@test.com",
  "password": "Test1234!",
  "name": "업체담당자",
  "phone": "01033334444",
  "role": "COMPANY_MANAGER",
  "hubId": null,
  "companyId": "22222222-2222-2222-2222-222222222222"
}

### internal API 테스트
GET http://localhost:58204/api/users/internal/2471adde-31ac-4274-83c0-cd6b8479a904

### HUB_MANAGER 자기 허브 생성
POST http://localhost:58509/api/companies
Content-Type: application/json
X-User-Id: 2471adde-31ac-4274-83c0-cd6b8479a904
X-User-Role: HUB_MANAGER

{
  "name": "허브매니저_다른허브_생성실패",
  "address": "서울시 강서구",
  "type": "RECIVER",
  "hubId": "22222222-2222-2222-2222-222222222222"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "hub@test.com",
  "password": "Test1234!"
}