@host = http://localhost:8080
@userId = 550e8400-e29b-41d4-a716-446655440000
@accessToken = 여기에 JWT토큰

# 1. 회원가입
### 회원가입
POST {{host}}/api/users
Content-Type: application/json

{
  "email": "testa@test.com",
  "password": "Password12!",
  "name": "홍길동",
  "phone": "010-1234-1208",
  "role": "HUB_MANAGER",
  "slackId": "hhon123",
  "hubId": "b0b87b6d-f4e0-48da-b87c-74c65cb6bca8",
  "companyId": null
}

### 2. 조회
### 내 정보 조회 (본인가능)
GET {{host}}/api/users/me
Authorization: Bearer {{accessToken}}

### 회원 단건 조회 (MASTER만 가능)
GET {{host}}/api/users/{{userId}}
Authorization: Bearer {{accessToken}}

### 회원 목록 조회 (MASTER만 가능)
GET {{host}}/api/users?page=0&size=10
Authorization: Bearer {{accessToken}}

### 대기 상태인 회원 목록 조회
GET {{host}}/api/users?status=PENDING&page=0&size=10
Authorization: Bearer {{accessToken}}


# 3. 수정
### 내 정보 수정
PATCH {{host}}/api/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "수정된 이름",
  "phone": "010-9999-9999",
  "slackId": "newSlack"
}

### 비밀번호 변경
PATCH {{host}}/api/users/me/password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "currentPassword": "BSA1234!",
  "newPassword": "Abcd1234!"
}


### 4. 상태 관리 (마스터, 허브매니저)

### 회원 승인
PATCH {{host}}/api/users/{{userId}}/status?status=APPROVED
Authorization: Bearer {{accessToken}}

### 회원 거절
PATCH {{host}}/api/users/{{userId}}/status?status=REJECTED
Authorization: Bearer {{accessToken}}


### 5. 삭제

### 회원 삭제 (MASTER)
DELETE {{host}}/api/users/{{userId}}
Authorization: Bearer {{accessToken}}

### 회원 탈퇴
DELETE {{host}}/api/users/me
Authorization: Bearer {{accessToken}}