spring:
  application:
    name: delivery-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: delivery
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

    data:
      redis:
        host: localhost
        port: 6379

kafka:
  bootstrap-servers: localhost:9092

  consumer:
    group-id: delivery-service-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retries: 3

  properties:
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.trusted.packages: "org.sixpang.*"

  topic:
    delivery-created: delivery.created

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id:
      ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


feature:
  user-service: true